from .model import Model
import json, os
from abacustest.lib_prepare.abacus import WriteKpt, WriteInput, ReadInput, AbacusStru, ReadKpt
from abacustest.constant import RECOMMAND_IMAGE, RECOMMAND_COMMAND, RECOMMAND_MACHINE

from typing import List, Dict, Any

import shutil, glob, copy
import numpy as np
from abacustest.lib_collectdata.collectdata import RESULT

_VOIGT_MODES = [
    ("xx", 0, 0), ("yy", 1, 1), ("zz", 2, 2),
    ("yz", 1, 2), ("xz", 0, 2), ("xy", 0, 1),
]


class PiezoelectricModel(Model):
    @staticmethod
    def prepare_args(parser):
        parser.description = "Prepare the inputs for piezoelectric tensor calculation."
        parser.add_argument('-j', '--job', default=[], action="extend", nargs="*", help='the paths of ABACUS jobs, should contain INPUT, STRU, or KPT, and pseudopotential and orbital files')
        parser.add_argument("--strain", default=0.01, type=float, help="The strain magnitude for finite difference calculation, default is 0.01.")
        parser.add_argument("--type", type=str, default="f", choices=["f", "b", "c"], help="The type of strain, f: forward strain, b: backward strain, c: central difference (both forward and backward strains). Default is f.")
        parser.add_argument("--no-k-continuity", action="store_true", help="Do not set use_k_continuity in NSCF calculations.")
        parser.add_argument("--relax", action="store_true", help="Relax atomic positions under each strain before Berry phase calculation (relaxed-ion). Default is clamped-ion.")
        parser.add_argument("--image", type=str, default=RECOMMAND_IMAGE, help="The image to use for the Bohrium job, default is %s" % RECOMMAND_IMAGE)
        parser.add_argument("--machine", type=str, default=RECOMMAND_MACHINE, help="The machine to use for the Bohrium job, default is 'c32_m64_cpu'.")
        parser.add_argument("--abacus_command", type=str, default=RECOMMAND_COMMAND, help=f"The command to run the Abacus job, default is '{RECOMMAND_COMMAND}'.")
        return parser
    
    
    def run_prepare(self,params):
        if not params.job:
            raise ValueError("No job specified, please use -j or --job to specify the job paths.")
        if params.strain <= 0:
            raise ValueError("Strain magnitude should be a positive value.")

        folders = prepare_piezoelectric_jobs(params.job, params.strain, params.type,
                                             k_continuity=not params.no_k_continuity,
                                             relax=params.relax)
        with open("run.sh", "w") as f1:
            if params.relax:
                f1.write(f"cp INPUT.relax INPUT\n{params.abacus_command} | tee relax.log\n")
                f1.write("cp OUT.ABACUS/STRU_ION_D STRU\n\n")
            f1.write(f"cp INPUT.scf INPUT\ncp KPT.scf KPT\n{params.abacus_command} | tee scf.log\n\n")
            for i in range(1,4):
                f1.write(f"cp INPUT.nscf{i} INPUT\ncp KPT.nscf{i} KPT\n{params.abacus_command} | tee nscf{i}.log\n")
                f1.write(f"mv OUT.ABACUS/running_nscf.log OUT.ABACUS/running_nscf{i}.log\nrm OUT.ABACUS/*.restart\n")
        
        setting = {
            "save_path": "results",
            "run_dft": [{
                "ifrun": True,
                "example": folders,
                "extra_files":["run.sh"],
                "command": "bash run.sh",
                "image": params.image,
                "bohrium": {"scass_type": params.machine, "job_type": "container", "platform": "ali"}
            }]
        } 
        
        setting_file = "setting.json"
        json.dump(setting, open(setting_file, "w"), indent=4)
        print("\nThe inputs are generated in", ", ".join(params.job))
        print(f"You can modify '{setting_file}' and 'run.sh', and execute below command to run the abacustest to submit all jobs to bohrium:\n\tabacustest submit -p setting.json\n")
        print(f"After finishing the calculations, you can enter the results directory, \nand run below command below to postprocess the piezoelectric tensor results:\n\tabacustest model piezoelectric post -j {' '.join(params.job)}\n")
        
    
    def postprocess_args(parser):
        parser.description = "Postprocess the piezoelectric tensor calculation results."
        parser.add_argument('-j', '--job', default=[], action="extend", nargs="*", help='the paths of the job directories, should contain the results of strained structures generated by the prepare step.')
        return parser   

    def run_postprocess(self,params):
        if not params.job:
            raise ValueError("No job specified, please use -j or --job to specify the job paths.")
        
        metrics, etensor = postprocess_piezoelectric(params.job)
        json.dump(etensor, open("metrics_piezoelectric.json", "w"), indent=4)
        json.dump(metrics, open("metrics.json", "w"), indent=4)
        print("\nThe piezoelectric tensor results are saved in 'metrics_piezoelectric.json'")

        import pandas as pd
        c = "Piezoelectric stress tensor e_{i,alpha} (C/m^2):\n"
        c += "Rows (i): polarization direction (x, y, z in Cartesian)\n"
        c += "Columns (alpha): Voigt strain mode (1=xx 2=yy 3=zz 4=yz 5=xz 6=xy)\n\n"
        for i, label in enumerate(["e_{x,alpha}", "e_{y,alpha}", "e_{z,alpha}"]):
            c += f"{label}  "
            c += "  ".join(f"{etensor[i][j]:9.4f}" for j in range(6))
            c += "\n"

        c += "\nNOTE: The piezoelectric stress tensor e_{i,alpha} is computed by finite difference,\n"
        c += "e_{i,alpha} = delta P_i / delta epsilon_alpha, where P_i is the polarization\n"
        c += "in Cartesian direction i (C/m^2), and epsilon_alpha is the Voigt strain component.\n"
        c += "Polarization is calculated via Berry phase method by ABACUS (berry_phase=1),\n"
        c += "and transformed from cell-vector basis to Cartesian coordinates.\n"
        c += "The polarization quantum ambiguity is resolved by comparing |delta P|\n"
        c += "with |delta P +/- mod| to select the minimal change.\n"
        with open("piezoelectric_summary.txt", "w") as f1:
            f1.write(c)
        print("\nSummary of piezoelectric tensor:")
        print(c)
            
        
        
def prepare_piezoelectric_jobs(jobs: List[str], strain: float, disp_type: str = "f",
                               k_continuity: bool = True, relax: bool = False) -> List[str]:
    if disp_type not in ["f", "b", "c"]:
        raise ValueError(f"Invalid displacement type: {disp_type}. Should be 'f', 'b', or 'c'.")
    if strain <= 0:
        raise ValueError("Strain magnitude should be a positive value.")
    
    folders = []
    for job in jobs:
        print("Preparing piezoelectric calculation for job path:", job)
        old_folders = [f for f in glob.glob(os.path.join(job, "piezoelectric_*")) if os.path.isdir(f)]
        if len(old_folders) > 0:
            print(f"Remove old piezoelectric_* folders in job path: {job}")
        for f in old_folders:
            shutil.rmtree(f)

        if not os.path.isfile(os.path.join(job, "STRU")):
            raise FileNotFoundError(f"STRU file not found in job path: {job}")
        if not os.path.isfile(os.path.join(job, "INPUT")):
            raise FileNotFoundError(f"INPUT file not found in job path: {job}")
        
        org_files = [f for f in os.listdir(job) if f not in ["INPUT", "STRU", "KPT"]]
        input_param = ReadInput(os.path.join(job, "INPUT"))
        stru_orig = AbacusStru.ReadStru(os.path.join(job, "STRU"))
        kpt, kpt_model = ReadKpt(job)
        input_param.pop("kspacing", None)
        input_param["suffix"] = "ABACUS"
        if os.path.isfile(os.path.join(job, "OUT.ABACUS/SPIN1_CHG.cube")):
            input_param["init_chg"] = "file"
        
        if disp_type != "c":
            org_path = os.path.join(job, "piezoelectric_org")
            os.makedirs(org_path, exist_ok=True)
            for f in org_files:
                os.symlink(os.path.abspath(os.path.join(job, f)), os.path.join(org_path, f))
            _write_piezo_inputs(org_path, stru_orig, input_param, kpt, kpt_model,
                                k_continuity=k_continuity, relax=relax)
            folders.append(org_path)
        
        cell_orig = np.array(stru_orig.get_cell(bohr=False))
        coords_frac = stru_orig.get_coord(bohr=False, direct=True)
        
        for label, i, j in _VOIGT_MODES:
            strain_3x3 = np.zeros((3, 3))
            strain_3x3[i, j] = strain
            strain_3x3[j, i] = strain

            if disp_type in ["f", "c"]:
                cell_pos = (np.eye(3) + strain_3x3) @ cell_orig
                stru_pos = copy.deepcopy(stru_orig)
                stru_pos.set_cell(cell_pos, bohr=False)
                stru_pos.set_coord(coords_frac, bohr=False, direct=True)
                
                pos_path = os.path.join(job, f"piezoelectric_{label}")
                os.makedirs(pos_path, exist_ok=True)
                for f in org_files:
                    os.symlink(os.path.abspath(os.path.join(job, f)), os.path.join(pos_path, f))
                with open(os.path.join(pos_path, "strain_metadata.json"), "w") as fm:
                    json.dump({"label": label, "magnitude": strain, "strain_3x3": strain_3x3.tolist()}, fm)
                _write_piezo_inputs(pos_path, stru_pos, input_param, kpt, kpt_model,
                                    k_continuity=k_continuity, relax=relax)
                folders.append(pos_path)
            
            if disp_type in ["b", "c"]:
                cell_neg = (np.eye(3) - strain_3x3) @ cell_orig
                stru_neg = copy.deepcopy(stru_orig)
                stru_neg.set_cell(cell_neg, bohr=False)
                stru_neg.set_coord(coords_frac, bohr=False, direct=True)
                
                neg_path = os.path.join(job, f"piezoelectric_{label}_back")
                os.makedirs(neg_path, exist_ok=True)
                for f in org_files:
                    os.symlink(os.path.abspath(os.path.join(job, f)), os.path.join(neg_path, f))
                with open(os.path.join(neg_path, "strain_metadata.json"), "w") as fm:
                    json.dump({"label": label, "magnitude": -strain, "strain_3x3": (-strain_3x3).tolist()}, fm)
                _write_piezo_inputs(neg_path, stru_neg, input_param, kpt, kpt_model,
                                    k_continuity=k_continuity, relax=relax)
                folders.append(neg_path)

    return folders


def _write_piezo_inputs(folder, stru, input_param, kpt, kpt_model, k_continuity=True, relax=False):
    input_param_copy = copy.deepcopy(input_param)
    input_param_copy["calculation"] = "scf"
    input_param_copy["out_chg"] = 1
    input_param_copy["out_bandgap"] = 1
    WriteInput(input_param_copy, os.path.join(folder, "INPUT.scf"))

    WriteKpt(kpt, os.path.join(folder, "KPT.scf"), kpt_model)

    if relax:
        input_param_copy["calculation"] = "relax"
        input_param_copy["out_chg"] = 1
        input_param_copy.pop("out_bandgap", None)
        WriteInput(input_param_copy, os.path.join(folder, "INPUT.relax"))

    input_param_copy["calculation"] = "nscf"
    input_param_copy["out_chg"] = None
    input_param_copy["init_chg"] = "file"
    input_param_copy["berry_phase"] = 1
    if k_continuity:
        input_param_copy["use_k_continuity"] = True
    for i in range(1, 4):
        input_param_copy["gdir"] = i
        WriteInput(input_param_copy, os.path.join(folder, f"INPUT.nscf{i}"))
    
    for i in range(3):
        kpt_nscf = copy.deepcopy(kpt)
        kpt_nscf[i] = 2 * kpt[i]
        WriteKpt(kpt_nscf, os.path.join(folder, f"KPT.nscf{i+1}"), kpt_model)
    
    stru.write(os.path.join(folder, "STRU"))


def postprocess_piezoelectric(jobs: List[str]):
    metrics = {}
    etensor = [[0.0 for _ in range(6)] for _ in range(3)]

    for job in jobs:
        print("Postprocessing piezoelectric calculation for job path:", job)
        if not os.path.isdir(job):
            print(f"Warning: job path {job} is not a directory, skip.")
            continue

        sub_folders = sorted([f for f in glob.glob(os.path.join(job, "piezoelectric_*")) 
                              if os.path.isdir(f)])

        pol_data = {}
        for folder in sub_folders:
            metrics[folder] = _read_scf_metrics(folder)
            name = os.path.basename(folder)
            P, mods, volume = _read_full_polarization(folder)
            pol_data[name] = {"P_cart": P, "mods": mods, "volume": volume}

        for mode, (label, i, j) in enumerate(_VOIGT_MODES):
            pos_dir = f"piezoelectric_{label}"
            neg_dir = f"piezoelectric_{label}_back"
            org_dir = "piezoelectric_org"

            has_pos = pos_dir in pol_data
            has_neg = neg_dir in pol_data
            has_org = org_dir in pol_data

            is_central = has_pos and has_neg
            is_forward = has_pos and has_org and not has_neg
            is_backward = has_neg and has_org and not has_pos

            if not (is_central or is_forward or is_backward):
                print(f"Warning: insufficient data for mode {mode}, skipping.")
                continue

            if is_central:
                P_pos = np.array(pol_data[pos_dir]["P_cart"])
                P_ref = np.array(pol_data[neg_dir]["P_cart"])
                mods_ref = np.array(pol_data[neg_dir]["mods"])
                denom = 2.0 * _get_strain_magnitude(job, pos_dir)
            elif is_forward:
                P_pos = np.array(pol_data[pos_dir]["P_cart"])
                P_ref = np.array(pol_data[org_dir]["P_cart"])
                mods_ref = np.array(pol_data[org_dir]["mods"])
                denom = _get_strain_magnitude(job, pos_dir)
            else:
                P_pos = np.array(pol_data[org_dir]["P_cart"])
                P_ref = np.array(pol_data[neg_dir]["P_cart"])
                mods_ref = np.array(pol_data[neg_dir]["mods"])
                denom = -_get_strain_magnitude(job, neg_dir)

            delta_P = P_pos - P_ref
            for k in range(3):
                if delta_P[k] > 0:
                    if abs(delta_P[k] - mods_ref[k]) < abs(delta_P[k]):
                        delta_P[k] -= mods_ref[k]
                else:
                    if abs(delta_P[k] + mods_ref[k]) < abs(delta_P[k]):
                        delta_P[k] += mods_ref[k]

            for k in range(3):
                etensor[k][mode] = float(delta_P[k]) / denom

    return metrics, etensor


def _read_full_polarization(folder):
    from abacustest.lib_model.model_016_bec import read_p, cal_polarization_cartesian
    
    p_vecs, mods, volumes = [], [], []
    for gdir in range(1, 4):
        logf = os.path.join(folder, "OUT.ABACUS", f"running_nscf{gdir}.log")
        if not os.path.isfile(logf):
            raise FileNotFoundError(f"NSCF log not found: {logf}")
        p_vec, mod, volume, _ = read_p(logf)
        p_vecs.append(p_vec)
        mods.append(mod)
        volumes.append(volume)

    stru = AbacusStru.ReadStru(os.path.join(folder, "STRU"))
    cell = stru.get_cell(bohr=False)
    P_cart = cal_polarization_cartesian(p_vecs, cell)
    return np.array(P_cart), np.array(mods), volumes[0]


def _get_strain_magnitude(job, dir_name):
    strain_file = os.path.join(job, dir_name, "strain_metadata.json")
    if os.path.isfile(strain_file):
        return json.load(open(strain_file))["magnitude"]
    raise FileNotFoundError(f"strain_metadata.json not found in {dir_name}.")


def _read_scf_metrics(job_dir):
    shutil.copy(os.path.join(job_dir, "INPUT.scf"), os.path.join(job_dir, "INPUT"))
    r = RESULT(path=job_dir, fmt="abacus", output=os.path.join(job_dir, "scf.log"))
    keys = ["normal_end", "converge", "energy", "scf_steps", "denergy_last", "drho_last", "band_gap"]
    return {k: r[k] for k in keys}
